### ISSUE TITLE
Enhance readability of Spring Integration configuration

### ISSUE THREAD

**Issue by petringo** [fmidev/aviation-message-archiver#52]
Reorganize Spring Integration configuration for better readability and maintainability.

**Comment by kasarit** [comment]
There is an actual bug related to the current Spring Integration configuration. When the source directory reading part of the flow is built in `MessageFileMonitorInitializer`, the directory polling starts before the complete Spring Integration configuration is constructed. This results in a bug when the application is started with files in source directories. Some of the source files may be read but not processed further because the integration flow is not complete.

This may somehow be related to the dynamic `IntegrationFlowContext` registrations in a `@PostConstruct` annotated method.
